# stage 1: install all dependencies
FROM node:19.8-alpine3.17  as dependencies
WORKDIR /app
COPY package.json ./
RUN npm install

# stage 2: test the code
FROM node:19.8-alpine3.17 as builder
WORKDIR /app
COPY --from=dependencies /app/node_modules ./node_modules
RUN npm test

# stage 3: install production dependencies
FROM node:19.8-alpine3.17 as prod-deps
WORKDIR /app
COPY package.json ./
RUN npm install --prod
CMD ["node", "app.js"]

# stage 4: run the program
FROM node:19.8-alpine3.17 as runner
WORKDIR /app
COPY --from=prod-deps /app/node_modules ./node_modules
COPY app.js ./
COPY tasks/ ./tasks
CMD ["node", "app.js"]
